### ISSUE TITLE
ghc-imported-from - GHC API and friends

### ISSUE THREAD

**Issue by carlohamalainen** [bfpg/talks#19]
<carlo_au> so I wrote this utility ghc-imported-from
    <carlo_au> and in the process of doing it I accidentally learned about the GHC API
    <carlo_au> so I could talk a bit about what it does, what I learned
    <carlo_au> and can angle it even at beginners by talking about how to read the types

**Comment by frasertweedale** [comment]
:+1:

**Comment by benkolera** [comment]
Thanks @carlohamalainen ! I hope that you kick some ass in Singapore! :)

**Comment by carlohamalainen** [comment]
@benkolera Here are my slides and demo code, can you fork it to the bfpg org? Thanks :)

https://github.com/carlohamalainen/bfpg-2015-08
