### ISSUE TITLE
Initial/Final Encodings

### ISSUE THREAD

**Issue by benkolera** [bfpg/talks#2]
Matt Peddie has volunteered. Just need to wait for him to accept the invite to assign this to him.

**Comment by peddie** [comment]
Fixed on 10/11/2015 (maybe you could close these issues with a link to the video/slides when they are available?)

**Comment by mdjnewman** [comment]
Closing - see http://talks.bfpg.org/talks/2015-11-10.initial_and_final_encodings.html :)
