### ISSUE TITLE
Zippers by Example

### ISSUE THREAD

**Issue by gwils** [bfpg/talks#26]
Immutable data-structures are the bread and butter of functional programming. Advantages of immutability include the persistence of old versions, the thread-safety, and the ability to reason about these structures. However, modifying data deep within a nested immutable structure can be costly in terms of performance.

Zippers allow for efficient traversal and modification of immutable data-structures. In this beginner-to-intermediate level talk, Zippers will be introduced in Scala. A successful practical application of zippers in the Argonaut JSON library will be examined.

**Comment by frasertweedale** [comment]
Beautiful!  When can we schedule this talk :)

**Comment by benkolera** [comment]
Oi @gwils I sent you an invite to join the speakers group ages ago. Plz accept so I can assign this to you. :)

**Comment by gwils** [comment]
@benkolera OK. I'm in!

**Comment by benkolera** [comment]
Ahah, you can't escape now!

**Comment by gwils** [comment]
The Matrix has me.
