### ISSUE TITLE
How to use Scalaz

### ISSUE THREAD

**Issue by gwils** [bfpg/talks#40]
Functional Programming in Scala by Bjarnason and Chiusano offers an excellent introduction to functional programming. However, the functional data structures and type classes shown within are largely missing from the scala standard library; they are found in the open source project scalaz.
This talk will introduce users to the typeclass pattern used extensively within scalaz and give an overview of the structure and layout of the library, as well as point users toward other useful resources.

**Comment by frasertweedale** [comment]
Might be a good topic for hack night / tutorial / workshop.

**Comment by gwils** [comment]
There was a time when I could have given this talk/tutorial/workshop, but my Scala and scalaz skills are rusty these days - scalaz was also planning on changing their typeclass mechanism in scalaz 8 (which I don't know the progress of). Beyond that, cats seems to be the dominant thing these days, and I have no experience with that library.

**Comment by frasertweedale** [comment]
OK, closing due to staleness :)
