### ISSUE TITLE
The importance of Types

### ISSUE THREAD

**Issue by hmijail** [bfpg/talks#43]
The BFPG has an F in its name, not a T. So why is everything SO Type-focused? 
Why Types seem to have taken over the Functional Programming paradigm? (have they?)
What is the difference between these Types and the types in C, Java, and such? 
Are there non-Functional Typed languages? 
OCaml can be used imperatively - does that matter for its Type system?
Does Scala use the type system of the JVM? Is it more powerful than the type system in Java?

**Comment by frasertweedale** [comment]
@hmijail do you want to present this topic, or are you requesting this topic? :)

**Comment by hmijail** [comment]
Requesting ;)

**Comment by frasertweedale** [comment]
Added "speaker wanted" tag :)

**Comment by donovancrichton** [comment]
Can we close this issue, now three years later, that I'm giving a talk on this topic in October? :)

**Comment by frasertweedale** [comment]
Yep.  Thanks!
