### ISSUE TITLE
The Erlang Ecosystem for Functional Programmers (and everyone else, too)

### ISSUE THREAD

**Issue by rellen** [bfpg/talks#45]
Erlang is a language rooted in the notion of concurrency and fault-tolerance, built on top of a flavour of dynamically-typed functional programming.  Since its open-sourcing, Erlang has spawned an ecosystem of dozens of functional programming languages that run on its VM (called the BEAM), and numerous tools to aid in developing robust software.
In this talk we will see what features some of the BEAM languages (specifically Elixir and Gleam), tools (Dialyzer, Gradualizer), and libraries (Witchcraft) have to offer functional programmers in their quest to write less wrong code.

Tentative agenda

- Brief history of Erlang (refer to 2013 talk for more detail) - 5mins
- Concepts of BEAM (runtime) and OTP (standard library++) - 10mins
- Elixir (immutability, HoF, protocols, pipelines, `with`, macros) - 15mins
- Proper/PropEx (property-based testing) - 5mins
- Dialyzer (success typing) - 5mins
- Gradualizer (gradual typing) - 5mins
- Witchcraft - 5mins
- Gleam - 5mins
- Set Theoretic Types?? - 5mins

**Comment by rellen** [comment]
cc @frasertweedale ^^^

**Comment by frasertweedale** [comment]
Thank you Rob!

**Comment by frasertweedale** [comment]
Thanks for your talk, @rellen.  Closing the ticket now :)
