### ISSUE TITLE
Meetup Costs

### ISSUE THREAD

**Issue by benkolera** [bfpg/talks#47]
Hey, the bfpg meetup costs $220USD/330 AUD per year.

Does anyone continuing the meetups want to take over paying this cost before November? 

![image](https://github.com/bfpg/talks/assets/159197/7eaf7157-b77c-424e-947b-8cd0dfd10cb0)

**Comment by frasertweedale** [comment]
Hi @benkolera, thanks for the heads-up.  Certainly you should no longer have to pay it!  I will discuss with current organisers and work out a plan.

**Comment by frasertweedale** [comment]
Hi @benkolera, I've paid the meetup.com account.  Thank you for all the years helping BFPG and especially for putting up the meetup costs all these years!
