### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by benkolera** [bfpg/talks#8]
Talk about functional like things that are useful for low level things.

**Comment by frasertweedale** [comment]
In such a talk it might be worth mentioning other efforts in this space, e.g. Ivory from Galois (Haskell DSL for safe low-level/embedded programming)

**Comment by dalaing** [comment]
I don't know if DDC fits in that space - the Rust / DDC combo would probably be better if the idea was to talk about region typing (in which case some talk of Oleg's lightweight monadic regions would probably come into play).

Ivory / Atom / Copilot would be great to hear about if the focus was on low level things.

**Comment by benkolera** [comment]
@doctau is going to talk about this in July and focus on Rust. :)
